### ISSUE TITLE
Textarea is displayed in the page

### ISSUE THREAD

**Issue by Waterloo** [MozillaKerala/Card-Generator#12]
![screenshot_2014-11-05-20-48-36](https://cloud.githubusercontent.com/assets/971925/4920025/ecab0bae-64fe-11e4-8926-10fdd3c36683.png)
 

The text area isn't hidden... And i don't know if the other frame is a bug / feature

**Comment by Mte90** [comment]
maybe a loading problem of the page?

**Comment by gabrielmicko** [comment]
It can not happen because its display:none;. Might occour while the page is loading, but it is normal.
