### ISSUE TITLE
SVG support

### ISSUE THREAD

**Issue by Mte90** [MozillaKerala/Card-Generator#33]
After a discussion with Elio Qoshi a problem of this generator that is not support the svg format file (library that convert in pdf).

https://discourse.mozilla-community.org/t/mozilla-business-cards/1775/2

I've opened the ticket for track this request, if in the future someone fix this problem.

**Comment by riverspirit** [comment]
Won't it be possible to have the svg design be converted into an html design, which can be used in the card generator?

**Comment by Mte90** [comment]
The problem is use for the images the svg version.

**Comment by riverspirit** [comment]
Oh, ok. The easiest workaround would be to convert the svg images to high quality png ones. I dunno if anyone will be able to look into adding svg support anytime soon.

**Comment by ThomasFarrow** [comment]
Maybe someone can clarify, why do we need SVG?

I feel like SVG would be a nice to have, but why not just use a correct scaled, 300DPI PNG file? Or even 600DPI, if you want to allow for people to buy "higher quality" business cards.

Sometimes, you have to look at the ratio of value:work needed. From just the information I have, I feel like that ratio would be something like 2:10. Anything below 7:10 I wouldn't say is worth the hassle ;)

But maybe I'm missing something

**Comment by Mte90** [comment]
SVG are better for the designer that create the design and also for create pdf that are really vector and not bitmap.

**Comment by Mte90** [comment]
I've forgotten to say that new version of dompdf in development support svg files https://github.com/dompdf/dompdf/issues/320

**Comment by elioqoshi** [comment]
Hey, can we look again into this?
If SVG is not doable let's do a HQ PNG image. Can we do this?
@Mte90 @riverspirit

**Comment by Mte90** [comment]
I have tried with the new version of dompdf but the card generator not work for the paper size problem.
I've opened a ticket https://github.com/dompdf/dompdf/issues/1070

**Comment by Mte90** [comment]
Ok i have started a porting to dompdf 0.7 :-)

**Comment by elioqoshi** [comment]
Super! Keep us in loop @Mte90 !

**Comment by Mte90** [comment]
Ported and merged the pr of dompdf 0.7 :-)
