### ISSUE TITLE
Font is not Open Sans

### ISSUE THREAD

**Issue by elioqoshi** [MozillaKerala/Card-Generator#34]
The text being output in the PDF (and in the browsers Preview) is not Open Sans but Arial.
Can we fix this so Open Sans is the default?

**Comment by Mte90** [comment]
Uhm as I can see in the fonts folder there is OpenSans.

**Comment by elioqoshi** [comment]
Hmm it still shows up as Arial...

**Comment by Mte90** [comment]
what version have you tried?

**Comment by elioqoshi** [comment]
Well  I tried the one online cards.mozillakerala.org

**Comment by Mte90** [comment]
The online version is not updated since like an year.

**Comment by elioqoshi** [comment]
Well, how can we test it then? Also, don't close the issue if it's nof fixed. People like me who are no programmers are felt excluded in these cases.

**Comment by Mte90** [comment]
Locally for me is working, we have to wait from Mozilla Kerala to update the online version :-)

**Comment by riverspirit** [comment]
@Waterloo, can you update pls?

**Comment by Waterloo** [comment]
Sorry for the late reply. actually i don't have the access to server to deploy the new version. I have verified the PR by @Mte90 locally and its working well.

**Comment by gabrielmicko** [comment]
The https://github.com/MozillaKerala/Card-Generator/pull/46 PR solves the problem.
