### ISSUE TITLE
dino head for Mozillians card

### ISSUE THREAD

**Issue by elioqoshi** [MozillaKerala/Card-Generator#37]
![bcard volunteer](https://cloud.githubusercontent.com/assets/5436686/11842995/5b7d70d8-a407-11e5-972c-c603c89107d0.jpg)

The image currently used for the Mozillians card is a bit outdated. Let's use the simpler dino head contour here.
Let me know what file format you need it.

**Comment by shinenelson** [comment]
SVG would ideal; since we were thinking of moving all [graphics to SVG](https://github.com/MozillaKerala/Card-Generator/issues/33)

**Comment by Mte90** [comment]
where i can found that svg?

**Comment by elioqoshi** [comment]
WIll send in a few hours.

**Comment by elioqoshi** [comment]
Here we go
https://dl.dropboxusercontent.com/u/62482708/Mozillians%20Dino.svg

**Comment by gabrielmicko** [comment]
@elioqoshi could you please upload all the PSD-s you have for this project?

**Comment by gabrielmicko** [comment]
Fixing this issue right now.
